// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGUeCuX5RTAMZboGFUN2AhXmPywwzB4Ro',
    appId: '1:13425842395:web:180c6bf0c958a0ec1ad4fe',
    messagingSenderId: '13425842395',
    projectId: 'doanmobile-app',
    authDomain: 'doanmobile-app.firebaseapp.com',
    storageBucket: 'doanmobile-app.firebasestorage.app',
    measurementId: 'G-S76V1HW9SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIavRzeMQO3sqrpHs7wzTWaqNi6YTbXBM',
    appId: '1:13425842395:android:4df8edcf8a44a7331ad4fe',
    messagingSenderId: '13425842395',
    projectId: 'doanmobile-app',
    storageBucket: 'doanmobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvtsXkg9sUTxgpXYYiiECWx71rWGoZgys',
    appId: '1:13425842395:ios:c4bd29cba86a50791ad4fe',
    messagingSenderId: '13425842395',
    projectId: 'doanmobile-app',
    storageBucket: 'doanmobile-app.firebasestorage.app',
    iosBundleId: 'com.example.doanmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvtsXkg9sUTxgpXYYiiECWx71rWGoZgys',
    appId: '1:13425842395:ios:c4bd29cba86a50791ad4fe',
    messagingSenderId: '13425842395',
    projectId: 'doanmobile-app',
    storageBucket: 'doanmobile-app.firebasestorage.app',
    iosBundleId: 'com.example.doanmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGUeCuX5RTAMZboGFUN2AhXmPywwzB4Ro',
    appId: '1:13425842395:web:28bae06e2bb2d4a51ad4fe',
    messagingSenderId: '13425842395',
    projectId: 'doanmobile-app',
    authDomain: 'doanmobile-app.firebaseapp.com',
    storageBucket: 'doanmobile-app.firebasestorage.app',
    measurementId: 'G-E1TE16S84B',
  );
}
